export const CREATE_PLAYER = "CREATE_PLAYER";
export const LOAD_PLAYERS_SUCCESS = "LOAD_PLAYERS_SUCCESS";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const UPDATE_PLAYERS_SUCCESS = "UPDATE_PLAYERS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_PLAYER_OPTIMISTIC = "DELETE_PLAYER_OPTIMISTIC";

export const LOAD_SESSIONS_SUCCESS = "LOAD_SESSIONS_SUCCESS";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";

export const LOAD_ROLLS_SUCCESS = "LOAD_ROLLS_SUCCESS";
export const CREATE_ROLL_SUCCESS = "CREATE_ROLL_SUCCESS";
